[dependencies]

[package]
  cjc-version = "0.55.3"
  compile-option = ""
  description = "Cache library for Cangjie"
  link-option = ""
  name = "cjcache"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "0.1.0"
  package-configuration = {}
